### ISSUE TITLE
Uptake newer versions of multi_json & oj (OR) relax version restrictions to minor instead of patch

### ISSUE THREAD

**Issue by santhoshkvuda** [splunk/fluent-plugin-kubernetes-metrics#130]
hi,

We are using this plugin along with few other Fluentd plugins and observed that very strict/exact version dependencies for the plugin dependencies not allowing us to uptake the newer versions. Would it be possible to uptake the newer versions available for multi_json and OJ ? OR it would be nice to relax the version restrictions to a minor version instead of patch ? i.e. replacing "multi_json ~> 1.14.1" with "multi_json ~> 1.14".

Thanks

**Comment by harshit-splunk** [comment]
https://github.com/splunk/fluent-plugin-kubernetes-metrics/pull/131

**Comment by santhoshkvuda** [comment]
Thanks.
