### ISSUE TITLE
URI::InvalidURIError

### ISSUE THREAD

**Issue by beth2016** [splunk/fluent-plugin-kubernetes-metrics#55]
I am getting this error:
2019-06-25 13:43:10 +0000 [error]: #0 Unexpected error raised. Stopping the timer. title=:metric_scraper error_class=URI::InvalidURIError error="bad URI(no host provided): https://:10250/stats/summary"
Looks like I am missing the host?  Where do I specify this?  
Thanks, any insight is appreciated.

**Comment by chaitanyaphalak** [comment]
How are you deploying this?

**Comment by beth2016** [comment]
i went back to previous version, and this issue went away.  thx

**Comment by fgranato** [comment]
Hello,
I've installed the last fluent-plugin-kubernetes-metrics:v1.1.2 using fluentd-docker-image:v1.8 ( alpine https://github.com/fluent/fluentd-docker-image/blob/master/v1.8/alpine/Dockerfile), but when we start the Fluentd on kubernates get the following error:
