### ISSUE TITLE
Metrics Subset

### ISSUE THREAD

**Issue by bdschaap** [splunk/fluent-plugin-kubernetes-metrics#69]
How would I go about filtering for just a subset of metrics?  I use Prometheus for short term metrics and Splunk for longer term trending.  However, I only want to ingest a small subset of the metrics.  Is this currently possible?

Thanks!

**Comment by chaitanyaphalak** [comment]
nope, its not supported.

**Comment by bdschaap** [comment]
Thanks.  For now I’m filtering metrics on the splunk heavy forwarder.

**Comment by rockb1017** [comment]
closing. thank you.
