### ISSUE TITLE
node_name "#{ENV['MY_NODE_NAME']}" is empty

### ISSUE THREAD

**Issue by fgranato** [splunk/fluent-plugin-kubernetes-metrics#70]
Hello,
I've installed the last fluent-plugin-kubernetes-metrics:v1.1.2 using fluentd-docker-image:v1.8 ( alpine https://github.com/fluent/fluentd-docker-image/blob/master/v1.8/alpine/Dockerfile), but when we start the Fluentd on kubernates get the following error:

**2020-01-24 11:10:20 +0000 [error]: #0 Unexpected error raised. Stopping the timer. title=:cadvisor_metric_scraper error_class=URI::InvalidURIError error="bad URI(no host provided): http://:10255/metrics/cadvisor"**

The fluent.conf contains the following configuration:

@type kubernetes_metrics
tag kubesystem.*
interval 10s
node_name "#{ENV['MY_NODE_NAME']}"
kubelet_port 10256
use_rest_client true
use_rest_client_ssl false
#insecure_ssl true
time_format %Y-%m-%dT%H:%M:%S.%NZ

And as you can note below, the environment properties are load correctly by server:

2020-01-24 11:09:30 +0000 [warn]: parameter 'time_format' in 
@type kubernetes_metrics
tag "kubesystem.*"
interval 10s
**node_name "aks-rancher-10595200-0"**
kubelet_port 10255
use_rest_client true
use_rest_client_ssl false
time_format %Y-%m-%dT%H:%M:%S.%NZ

Can you help me to investigate on this issue?

Thanks a lot

**Comment by rockb1017** [comment]
hello, it's been a while. sorry for late reply. Are you still having an issue? 
I think what needs to be specified is `kubelet_address` parameter.

**Comment by harshit-splunk** [comment]
Hey @fgranato, were you able to get proper node_name?

**Comment by harshit-splunk** [comment]
Closing the issue for now. Feel free to reopen or create a new one if needed.
