### ISSUE TITLE
Does it support custom metrics collection?

### ISSUE THREAD

**Issue by Bruslaan** [splunk/fluent-plugin-kubernetes-metrics#72]
Question:
Does it support custom metrics collection. I mean metrics beside this three sources
- The kubelet summary API
- The kubelet stats API
- The cAdvisor metrics API

Is it possible to configure it for custom metrics or is there maybe another plugin that makes this possible?

**Comment by SuitableProduce** [comment]
Is there an answer to this?

**Comment by mwang2016** [comment]
Hi, unfortunately we don't support custom metrics collection.

**Comment by harshit-splunk** [comment]
We do not support custom metric collection
