### ISSUE TITLE
no metrics for cadvisor

### ISSUE THREAD

**Issue by fengxx** [splunk/fluent-plugin-kubernetes-metrics#87]
**What happened**:
no metrics for cadvisor due to format issue
**What you expected to happen**:

https://github.com/splunk/fluent-plugin-kubernetes-metrics/blob/develop/lib/fluent/plugin/in_kubernetes_metrics.rb#L600-L631
it seems it looks for metrics with `container_name=` but cadvisor only have `container=, name=`, e.g.

```container_cpu_system_seconds_total{container="foo",id="id",name="name",namespace="foo",pod="pod-name"} 2356.13 1624427475226```

Changes related to Kubernetes 1.16 , pod_name and container_name metric labels removed from cAdvisor metrics.
https://github.com/kubernetes/enhancements/issues/1206
https://github.com/kubernetes/kubernetes/pull/80376

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.x
- Others:

**Comment by harshit-splunk** [comment]
Hey @fengxx 
Thanks for creating the issue. 
I have made changes in metric plugin and is already merged. So it will be available on next release.
Closing the issue. Feel free to reopen the issue or create a new one if needed.
