### ISSUE TITLE
inconsistent dimension for resouce request/usage

### ISSUE THREAD

**Issue by fengxx** [splunk/fluent-plugin-kubernetes-metrics#88]
**What happened**:

```
| mcatalog values(_dims)  where index=X metric_name=kube.container.cpu.request

  cluster_name
  extracted_source
  name
  namespace
  node

| mcatalog values(_dims)  where index=X metric_name=kube.container.cpu.usage

  cluster_name
  container-name
  extracted_source
  node
  pod-name
  pod-namespace
  pod-uid

shouldn't get align with container-name/name, pod-namespace/namespace?

same issue for kube.pod.cpu.request/kube.pod.cpu.usage
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
- Splunk version:
- Others:

**Comment by mwang2016** [comment]
Hi @fengxx, thank you for reporting this to us. However, we are not controlling the metadata but only transferring the data from Kubernetes.

**Comment by fengxx** [comment]
metadata is generated in the plugin, e.g. https://github.com/splunk/fluent-plugin-kubernetes-metrics/blob/9ee190c8a3825bcd7181904cc76e786f94f54d42/lib/fluent/plugin/in_kubernetes_metrics.rb#L557
